# Generated by Django 5.2.9 on 2025-12-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='booking_cancellation_window_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_scope',
            field=models.CharField(choices=[('ALL_VENDORS', 'All Vendors'), ('SELECTED_VENDORS', 'Selected Vendors')], default='ALL_VENDORS', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('BOOKING', 'Booking'), ('APP_ISSUE', 'App Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='payout_cycle',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('FLAT', 'Flat Amount'), ('PERCENT', 'Percentage')], default='PERCENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_onboard_vendor', models.BooleanField(default=True)),
                ('can_manage_bookings', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='superadmin.adminuser'),
        ),
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_doc_url', models.URLField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('gst_doc_url', models.URLField(blank=True)),
                ('bank_doc_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='superadmin.vendor')),
            ],
            options={
                'verbose_name': 'Vendor KYC',
                'verbose_name_plural': 'Vendor KYCs',
            },
        ),
    ]
