# Generated by Django 5.2.9 on 2025-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
