# Generated by Django 5.2.9 on 2025-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_add_coach_ecommerce_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Maximum total uses (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_usage_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Maximum uses per user'),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='new_user_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_category',
            field=models.CharField(choices=[('COURT_BOOKING', 'Court Booking'), ('COACHING', 'Coaching'), ('MEMBERSHIP', 'Membership'), ('ECOMMERCE', 'Ecommerce'), ('ALL', 'All Services')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Can be combined with other offers'),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Current usage count'),
        ),
        migrations.AddField(
            model_name='offer',
            name='visibility_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of users who can see this offer (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicable_scope',
            field=models.CharField(choices=[('ALL_VENDORS', 'All Vendors'), ('SELECTED_VENDORS', 'Selected Vendors'), ('ALL_SPORTS', 'All Sports'), ('SELECTED_SPORTS', 'Selected Sports'), ('ALL_VENUES', 'All Venues'), ('SELECTED_VENUES', 'Selected Venues')], default='ALL_VENDORS', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=20),
        ),
    ]
