# Generated by Django 5.2.9 on 2025-12-07 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_enhance_offer_fsd_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorkyc',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vendor KYC', 'verbose_name_plural': 'Vendor KYCs'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_proof_1_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_proof_1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_proof_2_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_proof_2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='license_proof_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('VENUE', 'Venue Owner'), ('COACH', 'Coach/Trainer'), ('ECOM', 'E-commerce Vendor'), ('VENUE_COACH', 'Venue + Coach'), ('VENUE_ECOM', 'Venue + E-commerce'), ('COACH_ECOM', 'Coach + E-commerce'), ('ALL', 'All Services')], default='VENUE', max_length=20),
        ),
    ]
