# Generated by Django 5.2.9 on 2025-12-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_vendorkyc_options_vendor_id_proof_1_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Sports Platform', max_length=200)),
                ('support_email', models.EmailField(default='support@sportsplatform.com', max_length=254)),
                ('support_phone', models.CharField(default='+91-9999999999', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('login_banner_message', models.TextField(blank=True)),
                ('global_terms_url', models.URLField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('default_commission_court', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('default_commission_coach', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('default_commission_ecommerce', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('default_commission_membership', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('max_upload_size_mb', models.IntegerField(default=10)),
                ('logo_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_commissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_memberships',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_payouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_vendors',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target', models.CharField(choices=[('ALL_VENDORS', 'All Vendors'), ('ALL_ADMINS', 'All Admins'), ('ALL', 'Everyone')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coach_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ecommerce_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('membership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commission Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admins',
            },
        ),
    ]
