# Generated by Django 5.2.9 on 2025-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_systemconfig_adminuser_can_manage_commissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='certificate_files',
            field=models.JSONField(default=list, help_text='List of certificate file URLs (max 5)'),
        ),
        migrations.AddField(
            model_name='coach',
            name='videos',
            field=models.JSONField(default=list, help_text='List of showcase video URLs (max 5)'),
        ),
    ]
